export { ReactComponent as IconLogo } from "components/Icon/storage/logo.svg"
export { ReactComponent as IconStatistic } from "components/Icon/storage/statistic.svg"
export { ReactComponent as IconArrowAccardion } from "components/Icon/storage/arrow-slider.svg"
export { ReactComponent as IconRobotTeacher } from "components/Icon/storage/teacher-robot.svg"
export { ReactComponent as IconInstagram } from "components/Icon/storage/instagram.svg"
